Moved to Styles.css
ducthienbui97/pullrequests pull request #13
Opened 2017-10-02 12:14 UTC by JipSterk

@ufocoder is this what you where looking for?
or would you like a seperate .css file for each component that needs styling?

2017-10-02 12:53 UTC, ufocoder commented
As variant it could be like your solution

2017-10-02 16:42 UTC, JipSterk commented
@ufocoder i don't know why codeclimate keeps failing.
Any suggestions?

2017-10-02 16:52 UTC, ufocoder commented
@JipSterk I'm still recommending you to adhere to this structure:
```
[component]:
 - index.js[x]
 - styles.css
 - image.png
```

Something like that I've described it the issue #9. Check it

2017-10-03 00:16 UTC, ducthienbui97 commented
There's conflict, can you update your repo?

2017-10-03 07:09 UTC, ducthienbui97 requested changes

2017-10-03 07:09 UTC, ducthienbui97 commented on src/components/User/styles.css
> +  margin-left: 0px;
Codeclimate is complaining "Values of 0 shouldn't have units specified."

2017-10-03 07:11 UTC, ducthienbui97 commented
Most of the complains were already there before.

2017-10-03 07:29 UTC, ducthienbui97 approved these changes

2017-10-03 07:41 UTC, merged